### PR TITLE
Fix orders synchronization algorithm.

### PR DESCRIPTION
**Pull request by zebimax**
In order to fix this Amazon orders integration with current master of Oro platform there have been made changes in the classes structure:
 - Remove unnecessary implementations of Amazon clients and interfaces and class that was responsible to aggregate these clients.(Amazon/Api/AmazonRestClient, Amazon/AbstractRestClientImpl, CheckRestClient, OrderItemsRestClient, OrderRestClient and their implementations).
I think these classes make orders loading complicated, so I decided to organize this work through one client (class Amazon/RestClient) which is only responsible for making requests to Amazon api with Guzzle client and controlling requests rate due to Amazon api requirements.
One client class also simplifies requests rate controlling, because all information of requests to api is now stored in one object and requests to different operations are handled properly (we can use time that was freed with recovery rate of one kind of operation for another one, i.e sleep time at ListOrderItems operation client also applies to handle ListOrders operation recovery rate).
Such implementation also increase encapsulation - all operations with Amazon api are performed through Amazon/RestClient which provides only necessary public interface to execute
its direct aim (sending requests)
 - Create NextTokenLoaderInterface and OrderLoader implementation,
which allows not to store all the order objects during one synchronization in Iterator and loader objects
(amount of order objects may be very big and leads to a huge memory usage).
NextTokenLoader and AmazonDataIteraor now can load and iterate order objects using the batch size parameter received from outside and does not save them after they have been stored in a DB.
 - Fix in OrderStrategy (case when some of items of existing orders were removed from order was not handled properly and items were not removed actually).

### CODE REVIEW

**Comment by kstupak** [comment]
@zebimax thank you for your contribution, we really appreciate it. 

We examined the proposed changes and found that they constitute nice improvement to the existing code. Though it would be nice to have an interface for RestClient in sake of the integrity of your patch.

**Comment by zebimax** [comment]
Your suggestion for the interface of RestClient is reasonable and I'll implement it in the nearest time.

**Comment by iklymenko** [comment]
@kstupak would be great to have new tagged version of the extension with these fixes to retain a backward compatibility with old version of the extension. Could you please create a tag 1.0.2?

**Comment by odi-um** [comment]
@iklymenko we have created tag 1.0.2 for version before your changes. Do you plan to contribute any other fixes? If not then we will raise dependencies to latest orocrm  and make another tag with changed major number as your changes were not backward compatible. 

Thank you.

**Comment by iklymenko** [comment]
@odi-um we also plan to add support of the channels.

**Comment by odi-um** [comment]
@iklymenko , i guess those changes won't be backwards incompatible. So i will create tag current state as 2.0.0, next pull request will be part of 2.1.0. Are there any objections from you or your team ?

**Comment by iklymenko** [comment]
@odi-um No objections. Thank You!

**Pull request merged**
